title: North Alabama Trans Support Group
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  TODO Do we need a description?
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
exclude:
  - deploy-key.enc
  - vendor
