title: Transgender North Alabama
email: webmistress@trans-north-alabama.org
description: >-
  A support group for trans people hosted in Huntsville and with members
  from Decatur, Athens, South Tennessee and the surrounding areas
baseurl: ""
url: "http://trans-north-alabama.org"
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
exclude:
  - deploy-key.enc
  - vendor
