[tool.poetry]
name = "nitori_org"
version = "0.1.0"
description = ""
authors = ["Jennifer Wilcox <jennifer@nitori.org>"]

[tool.poetry.dependencies]
python = "^3.6"
pelican = "^4.2"
markdown = "^3.2"
invoke = "^1.2"
webassets = "^2.0"
cssmin = "^0.2.0"
pyscss = "^1.3"


[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}
[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
